[PROXY]
; localproxy fetch URL
fetch = http://localhost/xhibit/proxy/xhibit_proxy.php
refresh = http://localhost/xhibit/proxy/xhibit_refresh.php
timeout = 3

[HOST]
macAddressCmd =  /sbin/ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'
defaultPage = NoInformationToDisplay.html
defaultMacAddress = b8:27:eb:67:75:8f
lastUpdatedLocation = /var/log/lastupdated.txt
timestampMonitorFile = /var/log/lastRun.txt